name: release

on:
  push:
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_tag: ${{ steps.check.outputs.is_tag }}

    steps:
      - name: Check if it's a tagged release
        id: check
        run: |
          REF=${{ github.ref }}
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${REF##*/}"
          StatusCode=$(curl -o -I -L -s -w "%{http_code}" -X GET -G $URL)
          echo $StatusCode
          if [[ "$StatusCode" == 200 ]]; then
            echo "This is tagged release!"
            echo "::set-output name=is_tag::no"
          else
            echo "This is a tag not release!"
            echo "::set-output name=is_tag::yes"
          fi
