name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    step:
      - name: Retrieve
        uses: actions/download-artifact@v2
        with:
          name: ERC_Output

